// Generated Feb 25, 2013 9:55:15 PM by Hibernate Tools 4.0.0
package com.hubble.store.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HubbleEnrichedAppDataId generated by hbm2java
 */
@Embeddable
public class HubbleEnrichedAppDataId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int hubbleAppId;
	private int appId;
	private String appKeywords;

	public HubbleEnrichedAppDataId() {
	}

	public HubbleEnrichedAppDataId(int hubbleAppId, int appId) {
		this.hubbleAppId = hubbleAppId;
		this.appId = appId;
	}

	public HubbleEnrichedAppDataId(int hubbleAppId, int appId,
			String appKeywords) {
		this.hubbleAppId = hubbleAppId;
		this.appId = appId;
		this.appKeywords = appKeywords;
	}

	@Column(name = "HUBBLE_APP_ID", nullable = false)
	public int getHubbleAppId() {
		return this.hubbleAppId;
	}

	public void setHubbleAppId(int hubbleAppId) {
		this.hubbleAppId = hubbleAppId;
	}

	@Column(name = "APP_ID", nullable = false)
	public int getAppId() {
		return this.appId;
	}

	public void setAppId(int appId) {
		this.appId = appId;
	}

	@Column(name = "APP_KEYWORDS", length = 65535)
	public String getAppKeywords() {
		return this.appKeywords;
	}

	public void setAppKeywords(String appKeywords) {
		this.appKeywords = appKeywords;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HubbleEnrichedAppDataId))
			return false;
		HubbleEnrichedAppDataId castOther = (HubbleEnrichedAppDataId) other;

		return (this.getHubbleAppId() == castOther.getHubbleAppId())
				&& (this.getAppId() == castOther.getAppId())
				&& ((this.getAppKeywords() == castOther.getAppKeywords()) || (this
						.getAppKeywords() != null
						&& castOther.getAppKeywords() != null && this
						.getAppKeywords().equals(castOther.getAppKeywords())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHubbleAppId();
		result = 37 * result + this.getAppId();
		result = 37
				* result
				+ (getAppKeywords() == null ? 0 : this.getAppKeywords()
						.hashCode());
		return result;
	}

}
