// Generated Feb 25, 2013 9:55:15 PM by Hibernate Tools 4.0.0
package com.hubble.store.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HubbleEnrichedAppData generated by hbm2java
 */
@Entity
@Table(name = "HUBBLE_ENRICHED_APP_DATA", catalog = "hubble")
public class HubbleEnrichedAppData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private HubbleEnrichedAppDataId id;
	private HubbleAppData hubbleAppData;

	public HubbleEnrichedAppData() {
	}

	public HubbleEnrichedAppData(HubbleEnrichedAppDataId id,
			HubbleAppData hubbleAppData) {
		this.id = id;
		this.hubbleAppData = hubbleAppData;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "hubbleAppId", column = @Column(name = "HUBBLE_APP_ID", nullable = false)),
			@AttributeOverride(name = "appId", column = @Column(name = "APP_ID", nullable = false)),
			@AttributeOverride(name = "appKeywords", column = @Column(name = "APP_KEYWORDS", length = 65535)) })
	public HubbleEnrichedAppDataId getId() {
		return this.id;
	}

	public void setId(HubbleEnrichedAppDataId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HUBBLE_APP_ID", nullable = false, insertable = false, updatable = false)
	public HubbleAppData getHubbleAppData() {
		return this.hubbleAppData;
	}

	public void setHubbleAppData(HubbleAppData hubbleAppData) {
		this.hubbleAppData = hubbleAppData;
	}

}
