package com.hubble.userprofile.hibernate;

// Generated Feb 23, 2013 11:18:08 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FacebookUserDemographics generated by hbm2java
 */
public class FacebookUserDemographics implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private FacebookUserDemographicsId id;
	private String username;
	private String interestedIn;
	private String locale;
	private String languages;
	private String currentLocation;
	private String meetingFor;
	private String political;
	private String relationshipStatus;
	private String religion;
	private String significantOther;
	private String timeZone;
	private String website;
	private String bio;
	private String email;
	private String thirdPartyId;
	private Date updatedTime;
	private Boolean verified;
	private byte[] work;

	public FacebookUserDemographics() {
	}

	public FacebookUserDemographics(FacebookUserDemographicsId id) {
		this.id = id;
	}

	public FacebookUserDemographics(FacebookUserDemographicsId id,
			String username, String interestedIn, String locale,
			String languages, String currentLocation, String meetingFor,
			String political, String relationshipStatus, String religion,
			String significantOther, String timeZone, String website,
			String bio, String email, String thirdPartyId, Date updatedTime,
			Boolean verified, byte[] work) {
		this.id = id;
		this.username = username;
		this.interestedIn = interestedIn;
		this.locale = locale;
		this.languages = languages;
		this.currentLocation = currentLocation;
		this.meetingFor = meetingFor;
		this.political = political;
		this.relationshipStatus = relationshipStatus;
		this.religion = religion;
		this.significantOther = significantOther;
		this.timeZone = timeZone;
		this.website = website;
		this.bio = bio;
		this.email = email;
		this.thirdPartyId = thirdPartyId;
		this.updatedTime = updatedTime;
		this.verified = verified;
		this.work = work;
	}

	public FacebookUserDemographicsId getId() {
		return this.id;
	}

	public void setId(FacebookUserDemographicsId id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getInterestedIn() {
		return this.interestedIn;
	}

	public void setInterestedIn(String interestedIn) {
		this.interestedIn = interestedIn;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public String getLanguages() {
		return this.languages;
	}

	public void setLanguages(String languages) {
		this.languages = languages;
	}

	public String getCurrentLocation() {
		return this.currentLocation;
	}

	public void setCurrentLocation(String currentLocation) {
		this.currentLocation = currentLocation;
	}

	public String getMeetingFor() {
		return this.meetingFor;
	}

	public void setMeetingFor(String meetingFor) {
		this.meetingFor = meetingFor;
	}

	public String getPolitical() {
		return this.political;
	}

	public void setPolitical(String political) {
		this.political = political;
	}

	public String getRelationshipStatus() {
		return this.relationshipStatus;
	}

	public void setRelationshipStatus(String relationshipStatus) {
		this.relationshipStatus = relationshipStatus;
	}

	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	public String getSignificantOther() {
		return this.significantOther;
	}

	public void setSignificantOther(String significantOther) {
		this.significantOther = significantOther;
	}

	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getBio() {
		return this.bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getThirdPartyId() {
		return this.thirdPartyId;
	}

	public void setThirdPartyId(String thirdPartyId) {
		this.thirdPartyId = thirdPartyId;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Boolean getVerified() {
		return this.verified;
	}

	public void setVerified(Boolean verified) {
		this.verified = verified;
	}

	public byte[] getWork() {
		return this.work;
	}

	public void setWork(byte[] work) {
		this.work = work;
	}

}
