package com.hubble.userprofile.hibernate;

// Generated Feb 23, 2013 11:18:08 AM by Hibernate Tools 3.4.0.CR1

/**
 * FbUserLikedEntities generated by hbm2java
 */
public class FbUserLikedEntities implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1520601630949141467L;
	private FbUserLikedEntitiesId id;

	public FbUserLikedEntities() {
	}

	public FbUserLikedEntities(FbUserLikedEntitiesId id) {
		this.id = id;
	}

	public FbUserLikedEntitiesId getId() {
		return this.id;
	}

	public void setId(FbUserLikedEntitiesId id) {
		this.id = id;
	}

}
