package com.hubble.userprofile.hibernate;

// Generated Mar 17, 2013 12:42:37 AM by Hibernate Tools 3.4.0.CR1

/**
 * FbUserLikedEntities generated by hbm2java
 */
public class FbUserLikedEntities implements java.io.Serializable {

	private FbUserLikedEntitiesId id;

	public FbUserLikedEntities() {
	}

	public FbUserLikedEntities(FbUserLikedEntitiesId id) {
		this.id = id;
	}

	public FbUserLikedEntitiesId getId() {
		return this.id;
	}

	public void setId(FbUserLikedEntitiesId id) {
		this.id = id;
	}

}
