package com.hubble.userprofile.hibernate;

// Generated Feb 23, 2013 11:18:08 AM by Hibernate Tools 3.4.0.CR1

/**
 * FbUserLikedEntitiesId generated by hbm2java
 */
public class FbUserLikedEntitiesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3336477907245628955L;
	private String fbEntityId;
	private String appId;

	public FbUserLikedEntitiesId() {
	}

	public FbUserLikedEntitiesId(String fbEntityId, String appId) {
		this.fbEntityId = fbEntityId;
		this.appId = appId;
	}

	public String getFbEntityId() {
		return this.fbEntityId;
	}

	public void setFbEntityId(String fbEntityId) {
		this.fbEntityId = fbEntityId;
	}

	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FbUserLikedEntitiesId))
			return false;
		FbUserLikedEntitiesId castOther = (FbUserLikedEntitiesId) other;

		return ((this.getFbEntityId() == castOther.getFbEntityId()) || (this
				.getFbEntityId() != null && castOther.getFbEntityId() != null && this
				.getFbEntityId().equals(castOther.getFbEntityId())))
				&& ((this.getAppId() == castOther.getAppId()) || (this
						.getAppId() != null && castOther.getAppId() != null && this
						.getAppId().equals(castOther.getAppId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFbEntityId() == null ? 0 : this.getFbEntityId()
						.hashCode());
		result = 37 * result
				+ (getAppId() == null ? 0 : this.getAppId().hashCode());
		return result;
	}

}
