package com.hubble.userprofile.hibernate;

// Generated Feb 23, 2013 11:18:08 AM by Hibernate Tools 3.4.0.CR1

/**
 * UserFriends generated by hbm2java
 */
public class UserFriends implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8696038425481631415L;
	private UserFriendsId id;

	public UserFriends() {
	}

	public UserFriends(UserFriendsId id) {
		this.id = id;
	}

	public UserFriendsId getId() {
		return this.id;
	}

	public void setId(UserFriendsId id) {
		this.id = id;
	}

}
