package com.hubble.userprofile.hibernate;

// Generated Mar 16, 2013 11:34:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserFriends generated by hbm2java
 */
public class UserFriends implements java.io.Serializable {

	private UserFriendsId id;

	public UserFriends() {
	}

	public UserFriends(UserFriendsId id) {
		this.id = id;
	}

	public UserFriendsId getId() {
		return this.id;
	}

	public void setId(UserFriendsId id) {
		this.id = id;
	}

}
